apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: e2t-bridge
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: e2t-bridge
            image: hvdveer/e2t
          restartPolicy: Never